name: 'Test Action'
description: 'Testing composite action'
inputs:
  solution:
    description: 'Name of solution'
    required: true
runs:
  using: "composite"
  steps:
  - name: Show something  
    shell: bash
    run: echo Hello ${{ inputs.solution }}
