name: Test Action
description: Testing composite action
inputs:
  solution-name:
    description: Solution file name
    required: true
  artifact-name:
    description: Artifact name
    required: true
runs:
  using: composite
  steps:
  - name: Add MSBuild to PATH
    uses: microsoft/setup-msbuild@v1.0.2

  - name: Build 64bit  
    shell: pwsh
    working-directory: ${{env.GITHUB_WORKSPACE}}
    run: msbuild /m "/p:Configuration=Release;Platform=x64;OutDir=output/win64/" "${{ inputs.solution-name }}"

  - name: Build 32bit
    shell: pwsh
    working-directory: ${{env.GITHUB_WORKSPACE}}
    run: msbuild /m "/p:Configuration=Release;Platform=x86;OutDir=output/win32/" "${{ inputs.solution-name }}"

  - name: Upload output files
    uses: actions/upload-artifact@v3
    with:
      name: ${{ inputs.artifact-name }}
      path: output
