name: MSBuild
on: [push]

env:
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build 64bit
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m "/p:Configuration=${{env.BUILD_CONFIGURATION}};Platform=x64;OutDir=bin\x64" .

    - name: Build 32bit
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m "/p:Configuration=${{env.BUILD_CONFIGURATION}};Platform=x86;OutDir=bin\x86" .

    - name: List files in the repository
      run: ls -r ${{ github.workspace }}
