name: PIBuild
on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: pguyot/arm-runner-action@v2
      with:
        copy_artifact_path: HelloWorld
        base_image: https://raspi.debian.net/tested/20230102_raspi_4_bullseye.img.xz
        commands: |
          make HelloWorld
          ls -a
    
    - name: Upload zip
      uses: actions/upload-artifact@v3
      with:
        name: HelloWorld_pi
        path: HelloWorld
